In [1]:
import trino

In [2]:
trino.__version__

'0.336.0'

In [3]:
conn = trino.dbapi.connect(
    host="trino",
    port=8080,
    user="jupyter",
    catalog="iceberg",
    schema="serving_db"
)

In [4]:
cur = conn.cursor()

In [5]:
cur.execute("SHOW TABLES")

In [6]:
print(cur.fetchall())

[['klines']]

In [8]:
cur.execute("SELECT * FROM klines LIMIT 5")
rows = cur.fetchall()
for row in rows:
    print(row)

[1948896, '2025-08-01 00:00:00', 1754006400328945, 115764.07, 115829.46, 115308.55, 115313.01, 302.159, 1754007299467573]
[1948897, '2025-08-01 00:15:00', 1754007300010950, 115313.01, 115933.0, 115313.0, 115800.01, 450.539, 1754008199447993]
[1948898, '2025-08-01 00:30:00', 1754008200077603, 115800.0, 115800.0, 115423.87, 115517.98, 184.425, 1754009099900832]
[1948899, '2025-08-01 00:45:00', 1754009100223687, 115517.99, 115527.53, 114313.13, 115427.27, 1589.765, 1754009999974074]
[1948900, '2025-08-01 01:00:00', 1754010000363342, 115427.27, 115609.99, 114600.0, 114649.9, 681.883, 1754010899995166]

In [9]:
import pandas as pd

In [10]:
cur.execute("SELECT * FROM klines LIMIT 10")
df = pd.DataFrame(cur.fetchall(), columns=[desc[0] for desc in cur.description])
df.head()

,group_id,group_date,open_time,open_price,high_price,low_price,close_price,volume,close_time
0,1948896,2025-08-01 00:00:00,1754006400328945,115764.07,115829.46,115308.55,115313.01,302.159,1754007299467573
1,1948897,2025-08-01 00:15:00,1754007300010950,115313.01,115933.00,115313.00,115800.01,450.539,1754008199447993
2,1948898,2025-08-01 00:30:00,1754008200077603,115800.00,115800.00,115423.87,115517.98,184.425,1754009099900832
3,1948903,2025-08-01 01:45:00,1754012700223622,115296.46,115407.71,115060.11,115331.86,258.534,1754013599937883
4,1948904,2025-08-01 02:00:00,1754013600005133,115328.67,115600.00,115221.07,115600.00,164.012,1754014499986628

In [12]:
cur.execute("SELECT count(*) FROM transform_db.aggtrades")
df = pd.DataFrame(cur.fetchall(), columns=[desc[0] for desc in cur.description])
df.head()

     _col0
0  1314072